# Generated by Django 6.0 on 2025-12-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonalreport',
            old_name='video_embed_url',
            new_name='poster_url',
        ),
    ]
