# Generated by Django 6.0 on 2025-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_video_embed_url_seasonalreport_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfiction',
            name='front_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
