# Generated by Django 6.0 on 2025-12-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fanfiction_front_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfiction',
            name='title',
            field=models.CharField(max_length=700),
        ),
    ]
