# Generated by Django 6.0 on 2025-12-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fanfiction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfiction',
            name='front_page_url',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
